# Generated by Django 6.0.2 on 2026-04-05 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('hr_name', models.CharField(blank=True, max_length=200, null=True)),
                ('package', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('required_skills', models.TextField()),
                ('description', models.TextField()),
                ('eligible_departments', models.CharField(blank=True, max_length=200, null=True)),
                ('min_percentage', models.FloatField(blank=True, null=True)),
                ('company_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_departments', models.CharField(max_length=200)),
                ('min_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('round1', 'Round 1'), ('round2', 'Round 2'), ('selected', 'Selected'), ('placed', 'Placed')], default='applied', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('skills', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('candidate_name', models.CharField(blank=True, max_length=150, null=True)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('candidate_id', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_location', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.resume')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('min_percentage', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('officer', 'Placement Officer')], default='student', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(max_length=255)),
                ('security_answer', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
