# Generated by Django 6.0.2 on 2026-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_college_userprofile_btech_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Student', max_length=10),
            preserve_default=False,
        ),
    ]
