# Generated by Django 6.0.2 on 2026-04-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
