# Generated by Django 6.0.2 on 2026-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userprofile_cgpa_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('not_attended', 'Not Attended')], default='applied', max_length=20),
        ),
    ]
